
CREATE TABLE category (
    standard_percentage NUMERIC(38, 2),
    category VARCHAR(255) NOT NULL,
    PRIMARY KEY (category)
);


CREATE TABLE employee (
    id INTEGER NOT NULL,
    name VARCHAR(255),
    rating INTEGER NOT NULL,
    category VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (category) REFERENCES category (category) 
);


CREATE TABLE appraisal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    actual_percentage NUMERIC(38, 2),
    deviation NUMERIC(38, 2),
    suggestion VARCHAR(255),
    FOREIGN KEY (employee_id) REFERENCES employee (id) 
);


INSERT INTO category (category, standard_percentage) VALUES
('A', 10.00), 
('B', 20.00), 
('C', 40.00), 
('D', 20.00), 
('E', 10.00); 


INSERT INTO employee (id, name, rating, category) VALUES
(5001, 'Harry', 1, 'A'),
(5002, 'John', 3, 'B'),
(5003, 'Doe', 4, 'C'),
(5004, 'Smith', 2, 'D'),
(5005, 'Jane', 5, 'E'),
(5006, 'Emily', 1, 'A'),
(5007, 'Lucas', 3, 'C'),
(5008, 'Ella', 4, 'D'),
(5009, 'Oliver', 2, 'B'),
(5010, 'Sophia', 5, 'E'),
(5011, 'Chloe', 1, 'A'),
(5012, 'Ethan', 3, 'C'),
(5013, 'Mia', 4, 'D'),
(5014, 'William', 2, 'C'),
(5015, 'Liam', 5, 'E');

